application: livecount
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on
- appstats: on

admin_console:
  pages:

inbound_services:
- warmup

handlers:
- url: /livecount/counter_admin
  script: livecount.counter_admin.app
  login: admin

- url: /livecount/.*
  script: livecount.counter.app
  login: admin
  
- url: /examples
  script: examples.app

# For convenience / demo only
# redirects to counter admin page
- url: .*
  script: livecount.counter.app
